name: bdd_night
source: fiftyone_zoo
zoo_name: bdd100k
splits:
  train: train
  val: validation
filters:
  time_of_day: [night]
class_policy: common_8
manifests:
  train: configs/manifests/bdd_night_train.json
  val: configs/manifests/bdd_night_val.json
exports:
  train: data/exports/bdd_night/train
  val: data/exports/bdd_night/val
